services:
  app:
    build: .
    container_name: api_testing_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - ENV_FILE=.env.local
    volumes:
      - .:/app
    restart: unless-stopped

  test:
    build: .
    container_name: api_testing_test
    command: pytest app/tests
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - ENV_FILE=.env.test
