name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    environment: test
    runs-on: ubuntu-latest

    env:
      APP_ENV: test
      ENV: test
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create .env.test file
        run: |
          cat <<EOF > .env.test
          ENV=test
          DB_HOST=${{ secrets.DB_HOST }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_HOST_BIND=127.0.0.1:5432
          EOF
      - name: Debug .env.test
        run: grep '^DB_HOST=' .env.test | cut -d '=' -f2-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Tests
        run: cat .env.test && APP_ENV=test make test
