name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ENV: ${{ secrets.ENV }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  ENV_FILE: .env

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests in Docker
        run: |
          docker compose up -d db
          sleep 5  # ensure DB is ready
          docker compose run --rm test
