name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    environment: test
    runs-on: ubuntu-latest

    env:
      ENV: test
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_HOST_BIND: ${{ secrets.DB_HOST_BIND }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create .env.test file
        run: |
          cat <<EOF > .env.test
          ENV=${ENV}
          LOG_LEVEL=${LOG_LEVEL}
          DB_HOST=${DB_HOST}
          DB_NAME=${DB_NAME}
          DB_USER=${DB_USER}
          DB_PASSWORD=${DB_PASSWORD}
          DB_HOST_BIND=${DB_HOST_BIND}
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Tests
        run: APP_ENV=test make test
